# Generated by Django 5.1.1 on 2025-01-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила')),
            ],
            options={
                'verbose_name': 'Заявка: перезвоните мне',
                'verbose_name_plural': 'Заявки: перезвоните мне',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FixIt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('problem', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила')),
            ],
            options={
                'verbose_name': 'Заявка: перезвоните мне',
                'verbose_name_plural': 'Заявки: перезвоните мне',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WantThis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('the_model', models.CharField(max_length=50, verbose_name='Марка машины')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила')),
            ],
            options={
                'verbose_name': 'Хочу такой же',
                'verbose_name_plural': 'Запросы: хочу такой же!',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='Haier', max_length=20, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марка',
                'ordering': ['brand'],
                'indexes': [models.Index(fields=['brand'], name='catalog_bra_brand_2aa66d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('the_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название модели')),
                ('seria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Серия')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price_old', models.IntegerField(blank=True, null=True, verbose_name='Цена БЕЗ скидки')),
                ('power_cold', models.CharField(blank=True, max_length=20, null=True, verbose_name='Охлаждение, Вт')),
                ('power_warm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Нагрев, Вт')),
                ('square', models.CharField(blank=True, max_length=20, null=True, verbose_name='Площадь')),
                ('temp_cold', models.CharField(blank=True, max_length=20, null=True, verbose_name='Охлаждение (С°)')),
                ('temp_warm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Нагрев (С°)')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Фото 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Фото 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Фото 3')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Фото 4')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Фото 5')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='catalog.brand', verbose_name='Марка')),
            ],
        ),
    ]
